export const cobrancas = [
  {
    id: "1",
    cliente_nome: "Sara Silva",
    usuario_id: "6415645",
    valor: 2000,
    data_vencimento: "27/10/2021",
    status: "vencida",
    descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "1",
    cliente_nome: "Sara Silva",
    usuario_id: "6415645",
    valor: 2000,
    data_vencimento: "27/10/2021",
    status: "emdia",
    descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "1",
    cliente_nome: "Sara Silva",
    usuario_id: "6415645",
    valor: 2000,
    data_vencimento: "27/10/2021",
    status: "pendente",
    descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "1",
    cliente_nome: "Sara Silva",
    usuario_id: "6415645",
    valor: 2000,
    data_vencimento: "27/10/2021",
    status: "vencida",
    descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];
